# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Accessibility
email: your-email@example.com
description: >- # "baseurl:"이 나올 때까지 줄 바꿈을 무시함
  Web Accessibility Testing Page
author: addmin
baseurl: "/home" # 사이트의 하위 경로, e.g. /blog
url: "https://jekyllblog.run.goorm.io" # 사이트의 기본 호스트 이름 및 프로토콜, e.g. http://example.com
# permalink: /:categories/:year/:month/:day/:title:output_ext
permalink: /:categories/:title/

# 언어 설정
lang: ko-KR

# 날짜 형식 지정(년.월.일 시:분:초 AM/PM)
date_format: "%Y.%m.%d"
date_time_format: "%Y.%m.%d %I:%M:%S %p"

# twitter_username: jekyllrb
github_username:  dlehdgh

# Build settings
theme: minima

markdown: kramdown
highlighter: rouge

paginate: 5 # 10
paginate_path: "/posts/page:num/"
paginate_size: 5

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# jekyll-paginate-multiple 깃허브 지원 안 됨
# paginate_multiple:
#   - paginate: 10
#     paginate_path: "/posts/page:num/"
#     sub_dir: "/posts"
#   - paginate: 10
#     paginate_path: "/tags/page:num/"
#     sub_dir: "/tags"
#   - paginate: 10
#     paginate_path: "/testing/page:num/"
#     sub_dir: '/testing'

# gems:
#   - jekyll-feed
#   - jekyll-paginate
#   - jekyll-paginate-multiple
# exclude:
#   - Gemfile
#   - Gemfile.lock

